// techTopics.ts
export interface TechTopic {
  id: number
  name: string
  emoji: string
}

export const techTopics: TechTopic[] = [
  { id: 1, name: "AWS", emoji: "☁️" },
  { id: 2, name: "Azure", emoji: "🔷" },
  { id: 3, name: "GCP", emoji: "🌐" },
  { id: 4, name: "Firebase", emoji: "🔥" },
  { id: 5, name: "Snowflake", emoji: "❄️" },
  { id: 6, name: "Databricks", emoji: "🧱" },
  { id: 7, name: "Spark", emoji: "⚡" },
  { id: 8, name: "Kafka", emoji: "🚀" },
  { id: 9, name: "Flink", emoji: "🌊" },
  { id: 10, name: "Airflow", emoji: "💨" },
  { id: 11, name: "Terraform", emoji: "🏗️" },
  { id: 12, name: "Kubernetes", emoji: "⚙️" },
  { id: 13, name: "Docker", emoji: "🐳" },
  { id: 14, name: "Istio", emoji: "🕸️" },
  { id: 15, name: "ArgoCD", emoji: "🎯" },
  { id: 16, name: "Prometheus", emoji: "📊" },
  { id: 17, name: "Grafana", emoji: "📈" },
  { id: 18, name: "ELK Stack", emoji: "🔍" },
  { id: 19, name: "Cloudflare", emoji: "🛡️" },
  { id: 20, name: "Okta", emoji: "🔐" },
  { id: 21, name: "Vault", emoji: "🔒" },
  { id: 22, name: "ServiceNow", emoji: "🎫" },
  { id: 23, name: "SAP S/4HANA", emoji: "💼" },
  { id: 24, name: "Oracle Fusion", emoji: "🏛️" },
  { id: 25, name: "Salesforce", emoji: "💰" },
  { id: 26, name: "Dynamics 365", emoji: "💻" },
  { id: 27, name: "UiPath", emoji: "🤖" },
  { id: 28, name: "Automation Anywhere", emoji: "⚡" },
  { id: 29, name: "Blue Prism", emoji: "🔵" },
  { id: 30, name: "TensorFlow", emoji: "🧠" },
  { id: 31, name: "PyTorch", emoji: "🔥" },
  { id: 32, name: "Transformers", emoji: "🤗" },
  { id: 33, name: "LangChain", emoji: "🔗" },
  { id: 34, name: "OpenAI", emoji: "🎨" },
  { id: 35, name: "MLflow", emoji: "📊" },
  { id: 36, name: "Kubeflow", emoji: "🌀" },
  { id: 37, name: "W&B", emoji: "📏" },
  { id: 38, name: "Vertex AI", emoji: "🌟" },
  { id: 39, name: "SageMaker", emoji: "🎯" },
  { id: 40, name: "Tableau", emoji: "📊" },
  { id: 41, name: "Power BI", emoji: "⚡" },
  { id: 42, name: "Looker", emoji: "👁️" },
  { id: 43, name: "Qlik Sense", emoji: "🎲" },
  { id: 44, name: "Palantir", emoji: "🔮" },
  { id: 45, name: "Confluent", emoji: "🌊" },
  { id: 46, name: "Snowplow", emoji: "🛷" },
  { id: 47, name: "Alteryx", emoji: "🔧" },
  { id: 48, name: "Informatica", emoji: "🔄" },
  { id: 49, name: "MuleSoft", emoji: "🔌" },
  { id: 50, name: "Neo4j", emoji: "🕸️" }
]