// system-design-topics.ts
export interface SystemDesignTopic {
  id: number
  name: string
  company: string
  emoji: string
}

export const systemDesignTopics: SystemDesignTopic[] = [
  { id: 1, name: "Scalable URL Shortener", company: "Bitly", emoji: "🔗" },
  { id: 2, name: "Search Engine Architecture", company: "Google Search", emoji: "🔍" },
  { id: 3, name: "Distributed File Storage", company: "Google File System (GFS)", emoji: "📁" },
  { id: 4, name: "Distributed Key-Value Store", company: "Amazon DynamoDB", emoji: "🗃️" },
  { id: 5, name: "Consistent Hashing & Partitioning", company: "Cassandra (Facebook)", emoji: "⚖️" },
  { id: 6, name: "Message Queues & Event Streaming", company: "Apache Kafka (LinkedIn)", emoji: "📨" },
  { id: 7, name: "Feed Generation System", company: "Facebook News Feed", emoji: "📰" },
  { id: 8, name: "Realtime Chat & Messaging", company: "WhatsApp, Slack", emoji: "💬" },
  { id: 9, name: "Realtime Collaboration Editing", company: "Google Docs (CRDTs)", emoji: "✍️" },
  { id: 10, name: "Video Streaming Platform", company: "YouTube, Twitch", emoji: "📹" },
  { id: 11, name: "Recommendation System", company: "Netflix Recommendations", emoji: "🎯" },
  { id: 12, name: "Ad Targeting System", company: "Google Ads, Facebook Ads", emoji: "🎪" },
  { id: 13, name: "Caching Systems", company: "Reddit, Twitter with Memcached", emoji: "⚡" },
  { id: 14, name: "Search Autocomplete", company: "Google Autocomplete", emoji: "🔮" },
  { id: 15, name: "Distributed Consensus & Locking", company: "Zookeeper", emoji: "🤝" },
  { id: 16, name: "API Gateway & Rate Limiting", company: "Twitter, Kong, Zuul (Netflix)", emoji: "🚪" },
  { id: 17, name: "E-commerce Order Management", company: "Amazon", emoji: "🛒" },
  { id: 18, name: "Inventory Management at Scale", company: "Walmart", emoji: "📦" },
  { id: 19, name: "Ride Matching & Dispatching", company: "Uber", emoji: "🚗" },
  { id: 20, name: "Surge Pricing Algorithm", company: "Uber", emoji: "💸" },
  { id: 21, name: "Food Delivery Platform", company: "DoorDash, Swiggy", emoji: "🍕" },
  { id: 22, name: "Payment Processing Systems", company: "PayPal, Visa", emoji: "💳" },
  { id: 23, name: "Digital Wallet & UPI Payments", company: "PhonePe, Google Pay", emoji: "📱" },
  { id: 24, name: "Fraud Detection Infrastructure", company: "Stripe", emoji: "🛡️" },
  { id: 25, name: "People You May Know", company: "LinkedIn", emoji: "👥" },
  { id: 26, name: "Job Search Ranking System", company: "LinkedIn Jobs", emoji: "💼" },
  { id: 27, name: "Realtime Analytics Pipelines", company: "Pinterest, LinkedIn", emoji: "📊" },
  { id: 28, name: "Data Warehouse Systems", company: "Google BigQuery", emoji: "🏢" },
  { id: 29, name: "Data Lake at Scale", company: "Uber Hadoop/Spark", emoji: "🏞️" },
  { id: 30, name: "Logging & Monitoring", company: "ELK Stack, Datadog", emoji: "📈" },
  { id: 31, name: "CI/CD Deployment Pipelines", company: "GitHub Actions", emoji: "🚀" },
  { id: 32, name: "Version Control at Scale", company: "GitHub, GitLab", emoji: "📝" },
  { id: 33, name: "Package Distribution System", company: "npm Registry, PyPI", emoji: "📚" },
  { id: 34, name: "Container Orchestration", company: "Kubernetes (Google)", emoji: "🐳" },
  { id: 35, name: "Microservices Architecture", company: "Netflix", emoji: "🧩" },
  { id: 36, name: "A/B Testing System", company: "Airbnb Experimentation", emoji: "🧪" },
  { id: 37, name: "Spam Filtering System", company: "Gmail Spam Filter", emoji: "🚫" },
  { id: 38, name: "Realtime Location Tracking", company: "Google Maps, Uber", emoji: "📍" },
  { id: 39, name: "Graph Database & Queries", company: "Facebook TAO, Neo4j", emoji: "🕸️" },
  { id: 40, name: "Bulk Notification Systems", company: "Mailchimp, AWS SES", emoji: "📬" },
  { id: 41, name: "Video/Media Processing", company: "TikTok Video Pipeline", emoji: "🎬" },
  { id: 42, name: "End-to-End Encryption", company: "WhatsApp Security", emoji: "🔐" },
  { id: 43, name: "Blockchain & Crypto", company: "Coinbase", emoji: "₿" },
  { id: 44, name: "Searchable Encrypted Data", company: "ProtonMail", emoji: "🔒" },
  { id: 45, name: "Knowledge Graph", company: "Google Knowledge Graph", emoji: "🧠" },
  { id: 46, name: "Voice Assistant Systems", company: "Alexa, Google Assistant", emoji: "🎤" },
  { id: 47, name: "Edge Computing", company: "Cloudflare Workers", emoji: "⚡" },
  { id: 48, name: "Disaster Recovery & Failover", company: "AWS Global Infra", emoji: "🌍" },
  { id: 49, name: "Data Replication & Sharding", company: "MongoDB, Google Spanner", emoji: "🔄" },
  { id: 50, name: "IoT Device Management", company: "Tesla OTA, AWS IoT Core", emoji: "🤖" },
  { id: 51, name: "Multi-Tenant SaaS", company: "Salesforce", emoji: "🏗️" },
  { id: 52, name: "Document Conflict Resolution", company: "Dropbox, Google Docs", emoji: "⚔️" },
  { id: 53, name: "Streaming Music Architecture", company: "Spotify", emoji: "🎵" },
  { id: 54, name: "Search Indexing", company: "Elasticsearch, Solr", emoji: "🔎" },
  { id: 55, name: "Data Privacy & GDPR", company: "Airbnb, Meta", emoji: "🛡️" },
  { id: 56, name: "Push Notification Service", company: "Apple Push Notifications", emoji: "🔔" },
  { id: 57, name: "Global Load Balancing", company: "Netflix Global Traffic", emoji: "⚖️" },
  { id: 58, name: "Realtime Fraud Detection", company: "Visa, Stripe ML", emoji: "🚨" },
  { id: 59, name: "Testing & Automation", company: "Google Borg Testing", emoji: "🔬" },
  { id: 60, name: "ML Personalization Platform", company: "Netflix & Airbnb ML", emoji: "🎭" }
]