name: Momma Meow

on:
  schedule:
    # 6:30 AM UTC
    - cron: "30 6 * * *"
    # 6:00 PM UTC
    - cron: "0 18 * * *"
    # Every 15 minutes
    - cron: "*/15 * * * *"
    # 10:00 PM UTC
    - cron: "0 22 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  api-calls:
    runs-on: ubuntu-latest
    steps:
      - name: Call Daily Topics API (6:30 AM)
        if: github.event.schedule == '30 6 * * *'
        run: |
          curl -X GET "https://9-lives.vercel.app/api/send/daily-topics?api_key=${{ secrets.API_KEY }}"

      - name: Call Reminder API (6:00 PM)
        if: github.event.schedule == '0 18 * * *'
        run: |
          curl -X GET "https://9-lives.vercel.app/api/send/reminder?api_key=${{ secrets.API_KEY }}"

      - name: Call Reply API (Every 15 mins)
        if: github.event.schedule == '*/15 * * * *'
        run: |
          curl -X GET "https://9-lives.vercel.app/api/send/reply?api_key=${{ secrets.API_KEY }}"

      - name: Call Roast API (10:00 PM)
        if: github.event.schedule == '0 22 * * *'
        run: |
          curl -X GET "https://9-lives.vercel.app/api/send/roast?api_key=${{ secrets.API_KEY }}"
