name: Scheduled API Link Pings with Sheet Logging

on:
  schedule:
    - cron: '0 */2 * * *'    # Java Code
    - cron: '30 */2 * * *'   # Python Code
    - cron: '0 1-23/2 * * *' # Java Theory
    - cron: '30 1-23/2 * * *' # Python Theory
  workflow_dispatch:

jobs:
  ping-and-log:
    runs-on: ubuntu-latest
    steps:
      - name: Call API and Log to Sheet
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SHEET_WEBHOOK: ${{ secrets.SHEET_WEBHOOK }}
        run: |
          run_and_log() {
            local URL=$1
            local TYPE=$2

            if curl -s --fail "$URL" > /dev/null; then
              STATUS="success"
            else
              STATUS="fail"
            fi

            curl -X POST -H "Content-Type: application/json" \
              -d "{\"type\": \"$TYPE\", \"status\": \"$STATUS\"}" \
              "$SHEET_WEBHOOK"
          }

          # Call each with different schedule match
          SCHEDULE="${{ github.event.schedule }}"
          case "$SCHEDULE" in
            "0 */2 * * *")
              run_and_log "https://9-lives.vercel.app/api/add/coding/java/code?api_key=$API_KEY" "java_code"
              ;;
            "30 */2 * * *")
              run_and_log "https://9-lives.vercel.app/api/add/coding/python/code?api_key=$API_KEY" "python_code"
              ;;
            "0 1-23/2 * * *")
              run_and_log "https://9-lives.vercel.app/api/add/coding/java/code?api_key=$API_KEY" "java_theory"
              ;;
            "30 1-23/2 * * *")
              run_and_log "https://9-lives.vercel.app/api/add/coding/python/code?api_key=$API_KEY" "python_theory"
              ;;
          esac
